name: netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2

      - name: install deps
        run: npm i --force

      - name: build
        run: npm run build

      - name: deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_APP}}
        run: >
          npx netlify deploy
          --prod
          --dir=dist
          --message=${{github.event.commits[0].message}}
